### ISSUE TITLE
Bug: `parseJson` doesn't accept an empty response

### ISSUE THREAD

**Issue by botenbreuk** [42BV/mad-spring-connect#28]
Sometimes an endpoint of a REST api return an empty response. When this happens the parseJson wants to return the response as a JSON, but this cannot be done when the response is empty and this wil throw a error.

**Comment by MrHus** [comment]
It does support handling empty responses, but the header must be set correctly to 204.

See: https://github.com/42BV/mad-spring-connect/blob/master/src/middleware.ts#L101
